### ISSUE TITLE
Level code OCR sometimes incorrect

### ISSUE THREAD

**Issue by dram55** [dram55/MarioMaker2OCR#14]
The ocr library will often confuse 5 for S and Q for 0.

Create and use a custom .traineddata file specific to the level code font.

**Comment by dram55** [comment]
Improved OCR in 0960e8563c995053973be462da5839239b371bd5,  1e4b6139f839f572c0b6891e0068a5711d0ee685, and dc1f374350662ee2ecead0c8d613a72e1529a9fe.

Still an open issue though. 

Switching from OcrEngineMode.TesseractOnly to OcrEngineMode.Default helped, but then created issues with some other level codes, for example 5HH-P92-5PF is now being read as **S**HH-P92-5PF.

Reading [this article](https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract-3.03%E2%80%933.05) it was suggested to not attempt to train a new library. Which is why I tried to fix it through image quality in the steps above. However after going through the [steps to improve image quality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#examples) it seems worth it to try and create a custom .traineddata. [Here](https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract-3.03%E2%80%933.05) and [here](https://pretius.com/how-to-prepare-training-files-for-tesseract-ocr-and-improve-characters-recognition/) are 2 links for reference on how to do this.

**Comment by dram55** [comment]
Significant improvements in 34538822cda3f3f6afcb9b22cf728b4bb82bf5ba with changing to OcrEngineMode.TesseractLstmCombined and also preparing the image in a way which increases font weight.

**Comment by dram55** [comment]
Still found some issue levels - too quick to close.

**Comment by underscore-zi** [comment]
B26-68G-BJG - 10 Coin Test. Be the best!

Read correctly on 720 and 1080 but not 480. 480 reads it as B26-68G-B1G

**Comment by dram55** [comment]
Good catch I'll add it as a test case. I think we're closing in on getting most level codes at this point.

**Comment by dram55** [comment]
I can't reproduce this. Was this on v1.0.25 or later? There was a change to the OCR 7/27 in 5887e6eab64d1ed81d9be8b5dcb7330bb9cd34a9, wondering if this error noticed before that commit. If not, I'm curious what the difference could be..
 
![image](https://user-images.githubusercontent.com/6719719/62002558-7c829a00-b0d4-11e9-8104-00b0f81e4840.png)

**Comment by dram55** [comment]
If it was on latest version, check log to see if it's falling back to original ocr method. I noticed in my testing a couple levels that did this. Need to adjust the width for GetStructuringElement() during character segmentation

**Comment by dram55** [comment]
I have not seen an issue with this since segmenting the characters before ocr. Closing issue.
