### ISSUE TITLE
Detect WR

### ISSUE THREAD

**Issue by dram55** [dram55/MarioMaker2OCR#31]
Idea that would be fun to implement eventually. Shouldn't be hard. Something like:
 - after clear screen detected
 - get 2 regions of screen (your time | wr time) 
 - use existing ImageLibrary.CompareImages()
 - if over 90% match then send WR event

**Comment by underscore-zi** [comment]
Another option would be to add the World Record banner that gets displayed as a template.

**Comment by dram55** [comment]
much simpler implementation - I like it

**Comment by dram55** [comment]
Closed in f3a7203
