### ISSUE TITLE
Clear event captured, but not sent to overlay

### ISSUE THREAD

**Issue by Hugobert** [dram55/MarioMaker2OCR#36]
Whenever I clear a level, it correctly appears in the application's log. However, the client does not receive a websocket message for the clear.

Edit: It also does not appear in the preview window - only in the log file.

**Comment by dram55** [comment]
Interesting. Do you have Chrome? If so could you try these steps

1) Open OBS and turn on virtual cam
1) Open and start MarioMaker2OCR program - for OBS-Camera device and port 3000
1) Open Chrome, go to http://localhost:3000/drambar
1) Press F12 for developer tools
1) Press Ctrl+F5 for refresh
1) I'd like to see a screenshot or copy paste from your console output (if any) within the DevTools.
1) Also interested in a screenshot of your _Network_ tab from within DevTools

Also try these steps for http://localhost:3000/smmbar 

Here is an example of what you'd expect to see
![image](https://user-images.githubusercontent.com/6719719/62124189-91f3f180-b297-11e9-9333-e8e838636ded.png)

I did run into an issue the other day where OBS Browser seemed flaky with connecting to the wss and after re-adding the source it fixed my issue. Not sure if related.

**Comment by dram55** [comment]
Fixed in 1.0.32 https://github.com/dram55/MarioMaker2OCR/releases/tag/1.0.32

**Comment by Hugobert** [comment]
Drambar works now, thanks a lot. Let me know if you still need logs & screenshots.
Smmbar now also gets the clear flag but doesn't stop the timer - I guess its main.js is just missing the required logic to stop the timer in the `case 'clear'` section.

**Comment by dram55** [comment]
Yup! Thanks for pointed that out as well - I wouldn't have noticed. Mostly due to implementing smmbar before the clear was around. I'll open another issue so I can do later and don't forget

**Comment by dram55** [comment]
Don't need logs+screenshots

**Comment by dram55** [comment]
actually im confused because it looks like it is in the code. ill still open an issue
