### ISSUE TITLE
Exception when reading Clear Timer

### ISSUE THREAD

**Issue by underscore-zi** [dram55/MarioMaker2OCR#38]
Unable to reproduce locally but was reported on discord.

```
2019-07-30 15:53:22,249 [9] ERROR MarioMaker2OCR.VideoProcessor - System.ArgumentOutOfRangeException: Der Index und die Länge müssen sich auf eine Position in der Zeichenfolge beziehen.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei MarioMaker2OCR.OCRLibrary.GetClearTimeFromFrame(Image`2 frame)
   bei MarioMaker2OCR.Form1.VideoProcessor_ClearScreen(Object sender, VideoEventArgs e)
   bei MarioMaker2OCR.VideoProcessor.onClearScreen(VideoEventArgs e)
   bei MarioMaker2OCR.VideoProcessor.processingLoop()
```

Looks like `doOCROnCharacterImages` isn't returning a smaller string than expected.

[MarioMaker2OCR.log](https://github.com/dram55/MarioMaker2OCR/files/3448015/MarioMaker2OCR.log)

Edit: received a video https://clips.twitch.tv/GrotesqueImportantBottleTwitchRaid

Probably because it uses the format 18:25,422 instead of 18'25''422 it was expecting.

**Comment by dram55** [comment]
wow! didn't realize the time was localized like that - good to know

**Comment by dram55** [comment]
https://github.com/dram55/MarioMaker2OCR/releases/tag/1.0.33 - addresses the crash. But not the issue of reading different localizations. Most likely will get bad clear times for now. Which shouldn't be an issue in the near term, since it isn't being used by any overlay.
