### ISSUE TITLE
ocrLevel.json not saved anymore

### ISSUE THREAD

**Issue by JanttuFi** [dram55/MarioMaker2OCR#45]
ocrLevel.json file isn't being saved anymore.
It seems this feature has been removed from the latest version. Would it be ok to get it back?

**Comment by dram55** [comment]
Wow! sorry I didn't think anyone was using it, glad you spoke up - I will add it back!

**Comment by dram55** [comment]
For now please use https://github.com/dram55/MarioMaker2OCR/releases/tag/1.0.51

**Comment by dram55** [comment]
https://github.com/dram55/MarioMaker2OCR/releases/tag/1.0.53 adds it back in the Settings Menu.

**Comment by JanttuFi** [comment]
Thanks for the quick reply. I use my own custom queue, and getting this file saved will make things so much easier for me. I reverted back to the old version. I was also thinking that when hitting the "Stop" button to stop the capture, how about make that clear the json file the same way as from File -> Clear level file?

**Comment by dram55** [comment]
Sure - right now you could capture that if you read the [websockets](https://github.com/dram55/MarioMaker2OCR#websocket-message-api) (along with deaths). For now, I will add the json equivalent to that in a future version.

**Comment by dram55** [comment]
Add Json support: https://github.com/dram55/MarioMaker2OCR/issues/46
