### ISSUE TITLE
Feature Request: Countdown instead of total time played

### ISSUE THREAD

**Issue by TybaIt** [dram55/MarioMaker2OCR#61]
Would it be possible to insert a setting for a countdown from a specific time (instead of total time played) and when that reaches zero make a sound? Would be helpful for streaming and limiting a level to a specific time.

When the setting is set it replaces the total time played.

**Comment by dram55** [comment]
Hey so this is somewhat implemented already. If you look at the settings file for whichever overlay you're using there are two fields regarding timer warning. That will play a sound after a specified time. https://github.com/dram55/MarioMaker2OCR/blob/master/MarioMaker2OCR/web/drambar/settings.js

Doing this, I think the timer will still count upwards though. This setting should help you out though. I guess it's kind of undocumented

**Comment by TybaIt** [comment]
Oh lol! Yeah I would not have found it as it's not in the settings, just in the settings file. Thanks

Could you make it count down as well?

**Comment by dram55** [comment]
Sure thing, I'll keep this issue open and get to it in the next week or so. 

Which web overlay are you using?

**Comment by TybaIt** [comment]
The [mario bar](https://raw.githubusercontent.com/dram55/MarioMaker2OCR/master/screenshots/mariobar.png) one.

**Comment by TybaIt** [comment]
Hopefully you get to it soon. <3

**Comment by dram55** [comment]
Hey @TybaIt thanks for the nudge, admittedly I forgot... 

Take the latest [release 1.0.72](https://github.com/dram55/MarioMaker2OCR/releases/tag/1.0.72) then modify `\MarioMaker2OCR\web\mariobar\settings.js`:
`playTimerWarning:true, ` (should the program play a sound when timer hits the limit)
`playTimerWarningAt:15, ` (time in minutes before playing the sound)
`timerDirection:1` (0 is count up, 1 is count down)

Then whatever file is sitting at `\MarioMaker2OCR\web\drambar\timer.mp3` will be played. Feel free to make this whatever you want, it just needs to have that filename and be in that folder. Note that it's in the **drambar** folder, even though it's not the overlay you're using. 

Pretty hacky fix but it should get the job done.
