### ISSUE TITLE
Settings Being Ignored

### ISSUE THREAD

**Issue by royaltongue** [dram55/MarioMaker2OCR#70]
I've made a copy of MarioBar, renaming the folder to "Recording", as I use MarioBar when livestreaming and want to keep them separate.
In the "Recording" folder, I've opened up  `settings.js` and set the following:
```
      // Which Components to see?
      isTimerVisible:true, 
      isDeathCountVisible:true,
      isLevelNameVisible:false,
      isLevelAuthorVisible:false,
      isLevelCodeVisible:false,
```

However, when going to `http://localhost:3000/recording`, it still shows the level code.

To further test this, I tried changing `slideFromDirection` from `left` to `right`, and this change also does not apply.

![image](https://user-images.githubusercontent.com/61848270/108476216-c8210980-725f-11eb-803c-b52452c1b057.png)
![image](https://user-images.githubusercontent.com/61848270/108476264-d40ccb80-725f-11eb-82e0-bdcf9e529afb.png)
![image](https://user-images.githubusercontent.com/61848270/108476293-dbcc7000-725f-11eb-8d07-62b2397e3e55.png)

**Comment by dram55** [comment]
Hey in web/recording/index.html line 12 please change to
`
<script src="/recording/settings.js"></script>`

Probably should have used relative paths to combat this.

**Comment by royaltongue** [comment]
That's it, thank you!
