### ISSUE TITLE
OBS Version 28 Breaks Virtual Cam - Need Alternatives

### ISSUE THREAD

**Issue by KilledWithStyle** [dram55/MarioMaker2OCR#80]
As the title states, OBS v28 breaks virtual cam. While I recognize that I could ""just"" install an older version, I would prefer to be using a better version of OBS. Do you know of any alternatives to OBS virtual cam?

**Comment by underscore-zi** [comment]
I don't know of any alternatives but I am now looking into getting this fixed.

**Comment by underscore-zi** [comment]
Sorry its taken so long, it looks like its an known issue that OBS Virtual Cam doesn't work with the DirectShow API that we need.

Fortunately, it looks like someone else has taken over updated the OBS Virtual Cam Plugin we were using: https://github.com/Avasam/obs-virtual-cam so you can use that now to get it back

**Comment by KilledWithStyle** [comment]
Thank you very much for the update. I appreciate your efforts. I was almost ready to track dram down on other platforms (other than twitter) but it looks like patience paid off.

I have tested this and it seems the new solution works. I hope the next plugin is continued to update for all future updates and thank you so much for your reply.
